# Set the appropriate branding and URL for OKD
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: console-config
  namespace: openshift-config-managed
data:
  console-config.yaml: |
    kind: ConsoleConfig
    apiVersion: console.openshift.io/v1
    customization:
      branding: okd
      documentationBaseURL: https://docs.okd.io/latest/
